export enum Roles {
  ADMIN = 'ADMIN',
  COMMUNITY_MANAGER = 'COMMUNITY_MANAGER',
  MANAGER = 'MANAGER',
  ADVISOR = 'ADVISOR',
  RECEPTIONIST = 'RECEPTIONIST',
  BANK_MANAGER = 'BANK_MANAGER',
  DEPUTY_SALES_MANAGER = 'DEPUTY_SALES_MANAGER',
  SUPERVISOR = 'SUPERVISOR',
  MANAGEMENT = 'MANAGEMENT',
}
