const API_BASE_URL = process.env.NODE_ENV === 'production' ? 'https://api.crm.sigurban.com/api' : 'http://localhost:3001/api/'

export const  Endpoints =  {
  DASHBOARD : API_BASE_URL + 'dashboard',
  EXPORT_DATA : API_BASE_URL + 'dashboard/export',
  LOGIN : API_BASE_URL + 'auth/login',
  REFRESH_TOKEN : API_BASE_URL + 'auth/refresh-token',
  USER : API_BASE_URL + 'users',
  EDIT_USER : API_BASE_URL + 'user/edit/',
  DELETE_USER : API_BASE_URL + 'user/delete/',
  CAMPAIGN : API_BASE_URL + 'campaign/',
  ADMIN_LEADS : API_BASE_URL + 'leads',
  ASSIGN_LEAD_ADVISOR : API_BASE_URL + 'leads/assign/advisor/',
  ASSIGN_LEAD_CAMPAIGN : API_BASE_URL + 'leads/assign/campaign/',
  REJECTED_BANK : API_BASE_URL + 'leads/rejected-banks/',
  ADVISOR_LEADS : API_BASE_URL + 'leads/advisor/',
  MANAGER_LEADS : API_BASE_URL + 'leads/manager/',
  BANK_MANAGER_LEADS : API_BASE_URL + 'leads/bank-manager/',
  RECEPTIONIST_LEADS : API_BASE_URL + 'leads/receptionist/without-advisor/',
  LEAD : API_BASE_URL + 'leads/',
  LEAD_STATUS : API_BASE_URL + 'leads/status/',
  LEAD_REVERT_STATUS : API_BASE_URL + 'leads/status/revert/',
  LEAD_BY_USER : API_BASE_URL + 'leads/user/',
  NOTIFICATIONS : API_BASE_URL + 'notifications/',
  BANK : API_BASE_URL + 'banks',
  PROJECTS: API_BASE_URL + 'projects/',
  PROJECTS_AVAILABLE: API_BASE_URL + 'projects/available',
  LOTS : API_BASE_URL + 'lots/',
  LOTS_BY_PROJECT: API_BASE_URL + 'lots/project/',
  REQUIREMENT: API_BASE_URL + 'requirements',
  ROLES: API_BASE_URL + 'roles',
  SETTINGS: API_BASE_URL + 'settings',
  SETTINGS_GOAL_GENERAL: API_BASE_URL + 'settings/general-goals',
  SETTINGS_GOAL_ADVISOR: API_BASE_URL + 'settings/individual-goals',
}
