version: '3.1'

services:
  database:
    image: mongo:latest
    container_name: sigurban_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    restart: always
    env_file:
      - ./.env
    ports:
      - 27019:27017
    volumes:
      -  ../data/db:/data/db
